actions:
- action_type: JointAction
  clip: null
  dtype: torch.float32
  extras:
    description: Joint action term that applies the processed actions to the articulation's
      joints as position commands.
  full_path: isaaclab.envs.mdp.actions.joint_actions.JointPositionAction
  joint_names:
  - FL_hip_joint
  - FR_hip_joint
  - RL_hip_joint
  - RR_hip_joint
  - FL_thigh_joint
  - FR_thigh_joint
  - RL_thigh_joint
  - RR_thigh_joint
  - FL_calf_joint
  - FR_calf_joint
  - RL_calf_joint
  - RR_calf_joint
  mdp_type: Action
  name: joint_position_action
  offset:
  - 0.10000000149011612
  - -0.10000000149011612
  - 0.10000000149011612
  - -0.10000000149011612
  - 0.800000011920929
  - 0.800000011920929
  - 1.0
  - 1.0
  - -1.5
  - -1.5
  - -1.5
  - -1.5
  scale: 0.25
  shape:
  - 12
articulations:
  robot:
    default_joint_armature:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    default_joint_damping:
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    - 0.5
    default_joint_friction:
    - 0.009999999776482582
    - 0.009999999776482582
    - 0.009999999776482582
    - 0.009999999776482582
    - 0.009999999776482582
    - 0.009999999776482582
    - 0.009999999776482582
    - 0.009999999776482582
    - 0.009999999776482582
    - 0.009999999776482582
    - 0.009999999776482582
    - 0.009999999776482582
    default_joint_pos:
    - 0.10000000149011612
    - -0.10000000149011612
    - 0.10000000149011612
    - -0.10000000149011612
    - 0.800000011920929
    - 0.800000011920929
    - 1.0
    - 1.0
    - -1.5
    - -1.5
    - -1.5
    - -1.5
    default_joint_pos_limits:
    - - -1.0471998453140259
      - 1.0471998453140259
    - - -1.0471998453140259
      - 1.0471998453140259
    - - -1.0471998453140259
      - 1.0471998453140259
    - - -1.0471998453140259
      - 1.0471998453140259
    - - -1.5707999467849731
      - 3.4906997680664062
    - - -1.5707999467849731
      - 3.4906997680664062
    - - -0.5235999226570129
      - 4.537899494171143
    - - -0.5235999226570129
      - 4.537899494171143
    - - -2.7227001190185547
      - -0.8377599120140076
    - - -2.7227001190185547
      - -0.8377599120140076
    - - -2.7227001190185547
      - -0.8377599120140076
    - - -2.7227001190185547
      - -0.8377599120140076
    default_joint_stiffness:
    - 25.0
    - 25.0
    - 25.0
    - 25.0
    - 25.0
    - 25.0
    - 25.0
    - 25.0
    - 25.0
    - 25.0
    - 25.0
    - 25.0
    default_joint_vel:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    joint_names:
    - FL_hip_joint
    - FR_hip_joint
    - RL_hip_joint
    - RR_hip_joint
    - FL_thigh_joint
    - FR_thigh_joint
    - RL_thigh_joint
    - RR_thigh_joint
    - FL_calf_joint
    - FR_calf_joint
    - RL_calf_joint
    - RR_calf_joint
observations:
  policy:
  - dtype: torch.float32
    extras:
      axes:
      - X
      - Y
      - Z
      description: Root angular velocity in the asset's root frame.
      modifiers: null
      units: rad/s
    full_path: isaaclab.envs.mdp.observations.base_ang_vel
    mdp_type: Observation
    name: base_ang_vel
    observation_type: RootState
    overloads:
      clip: null
      flatten_history_dim: true
      history_length: 5
      scale: null
    shape:
    - 3
  - dtype: torch.float32
    extras:
      axes:
      - X
      - Y
      - Z
      description: Gravity projection on the asset's root frame.
      modifiers: null
      units: m/s^2
    full_path: isaaclab.envs.mdp.observations.projected_gravity
    mdp_type: Observation
    name: projected_gravity
    observation_type: RootState
    overloads:
      clip: null
      flatten_history_dim: true
      history_length: 5
      scale: null
    shape:
    - 3
  - dtype: torch.float32
    extras:
      description: The generated command from command term in the command manager
        with the given name.
      modifiers: null
    full_path: isaaclab.envs.mdp.observations.generated_commands
    mdp_type: Observation
    name: generated_commands
    observation_type: Command
    overloads:
      clip: null
      flatten_history_dim: true
      history_length: 5
      scale: null
    shape:
    - 3
  - dtype: torch.float32
    extras:
      description: 'The joint positions of the asset w.r.t. the default joint positions.
        Note: Only the joints configured in :attr:`asset_cfg.joint_ids` will have
        their positions returned.'
      modifiers: null
      units: rad
    full_path: isaaclab.envs.mdp.observations.joint_pos_rel
    joint_names:
    - FL_hip_joint
    - FR_hip_joint
    - RL_hip_joint
    - RR_hip_joint
    - FL_thigh_joint
    - FR_thigh_joint
    - RL_thigh_joint
    - RR_thigh_joint
    - FL_calf_joint
    - FR_calf_joint
    - RL_calf_joint
    - RR_calf_joint
    joint_pos_offsets:
    - 0.10000000149011612
    - -0.10000000149011612
    - 0.10000000149011612
    - -0.10000000149011612
    - 0.800000011920929
    - 0.800000011920929
    - 1.0
    - 1.0
    - -1.5
    - -1.5
    - -1.5
    - -1.5
    mdp_type: Observation
    name: joint_pos_rel
    observation_type: JointState
    overloads:
      clip: null
      flatten_history_dim: true
      history_length: 5
      scale: null
    shape:
    - 12
  - dtype: torch.float32
    extras:
      description: 'The joint velocities of the asset w.r.t. the default joint velocities.
        Note: Only the joints configured in :attr:`asset_cfg.joint_ids` will have
        their velocities returned.'
      modifiers: null
      units: rad/s
    full_path: isaaclab.envs.mdp.observations.joint_vel_rel
    joint_names:
    - FL_hip_joint
    - FR_hip_joint
    - RL_hip_joint
    - RR_hip_joint
    - FL_thigh_joint
    - FR_thigh_joint
    - RL_thigh_joint
    - RR_thigh_joint
    - FL_calf_joint
    - FR_calf_joint
    - RL_calf_joint
    - RR_calf_joint
    joint_vel_offsets:
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    - 0.0
    mdp_type: Observation
    name: joint_vel_rel
    observation_type: JointState
    overloads:
      clip: null
      flatten_history_dim: true
      history_length: 5
      scale: null
    shape:
    - 12
  - dtype: torch.float32
    extras:
      description: The last input action to the environment. The name of the action
        term for which the action is required. If None, the entire action tensor is
        returned.
      modifiers: null
    full_path: isaaclab.envs.mdp.observations.last_action
    mdp_type: Observation
    name: last_action
    observation_type: Action
    overloads:
      clip: null
      flatten_history_dim: true
      history_length: 5
      scale: null
    shape:
    - 12
scene:
  decimation: 4
  dt: 0.02
  physics_dt: 0.005
