controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    
    imu_state_broadcaster:
      type: imu_sensor_broadcaster/IMUSensorBroadcaster

    stand_static_controller:
      type: legged_ros2_controller/StaticController

    sit_static_controller:
      type: legged_ros2_controller/StaticController

    rl_controller:
      type: legged_rl_controller/LeggedRLController

joint_state_broadcaster:
  ros__parameters:
    update_rate: 250
    joints: [
      'FL_hip_joint', 
      'FL_thigh_joint', 
      'FL_calf_joint', 
      'FR_hip_joint', 
      'FR_thigh_joint', 
      'FR_calf_joint', 
      'RL_hip_joint', 
      'RL_thigh_joint', 
      'RL_calf_joint', 
      'RR_hip_joint', 
      'RR_thigh_joint', 
      'RR_calf_joint'
    ]
    interfaces:
      - position
      - velocity
      - effort
      - position_des
      - velocity_des

imu_state_broadcaster:
  ros__parameters:
    sensor_name: "imu"
    frame_id:  "imu_link"


stand_static_controller:
  ros__parameters:
    update_rate: 50
    traj_time: 5.0  # Time of joint trajectory in seconds
    joint_names: [
      'FL_hip_joint', 
      'FL_thigh_joint', 
      'FL_calf_joint', 
      'FR_hip_joint', 
      'FR_thigh_joint', 
      'FR_calf_joint', 
      'RL_hip_joint', 
      'RL_thigh_joint', 
      'RL_calf_joint', 
      'RR_hip_joint', 
      'RR_thigh_joint', 
      'RR_calf_joint'
    ]
    joint_cfg:
      FL_hip_joint:
        kp: 25.0
        kd: 0.5
        default_pos: 0.10000000149011612
      FR_hip_joint:
        kp: 25.0
        kd: 0.5
        default_pos: -0.10000000149011612
      RL_hip_joint:
        kp: 25.0
        kd: 0.5
        default_pos: 0.10000000149011612
      RR_hip_joint:
        kp: 25.0
        kd: 0.5
        default_pos: -0.10000000149011612
      FL_thigh_joint:
        kp: 25.0
        kd: 0.5
        default_pos: 0.800000011920929
      FR_thigh_joint:
        kp: 25.0
        kd: 0.5
        default_pos: 0.800000011920929
      RL_thigh_joint:
        kp: 25.0
        kd: 0.5
        default_pos: 1.0
      RR_thigh_joint:
        kp: 25.0
        kd: 0.5
        default_pos: 1.0
      FL_calf_joint:
        kp: 25.0
        kd: 0.5
        default_pos: -1.5
      FR_calf_joint:
        kp: 25.0
        kd: 0.5
        default_pos: -1.5
      RL_calf_joint:
        kp: 25.0
        kd: 0.5
        default_pos: -1.5
      RR_calf_joint:
        kp: 25.0
        kd: 0.5
        default_pos: -1.5


sit_static_controller:
  ros__parameters:
    update_rate: 50
    traj_time: 5.0  # Time of joint trajectory in seconds
    joint_names: [
      'FL_hip_joint', 
      'FL_thigh_joint', 
      'FL_calf_joint', 
      'FR_hip_joint', 
      'FR_thigh_joint', 
      'FR_calf_joint', 
      'RL_hip_joint', 
      'RL_thigh_joint', 
      'RL_calf_joint', 
      'RR_hip_joint', 
      'RR_thigh_joint', 
      'RR_calf_joint'
    ]
    joint_cfg:
      FL_hip_joint:
        kp: 25.0
        kd: 0.5
        default_pos: 0.10000000149011612
      FR_hip_joint:
        kp: 25.0
        kd: 0.5
        default_pos: -0.10000000149011612
      RL_hip_joint:
        kp: 25.0
        kd: 0.5
        default_pos: 0.10000000149011612
      RR_hip_joint:
        kp: 25.0
        kd: 0.5
        default_pos: -0.10000000149011612
      FL_thigh_joint:
        kp: 25.0
        kd: 0.5
        default_pos: 1.30
      FR_thigh_joint:
        kp: 25.0
        kd: 0.5
        default_pos: 1.30
      RL_thigh_joint:
        kp: 25.0
        kd: 0.5
        default_pos: 1.30
      RR_thigh_joint:
        kp: 25.0
        kd: 0.5
        default_pos: 1.30
      FL_calf_joint:
        kp: 25.0
        kd: 0.5
        default_pos: -2.4
      FR_calf_joint:
        kp: 25.0
        kd: 0.5
        default_pos: -2.4
      RL_calf_joint:
        kp: 25.0
        kd: 0.5
        default_pos: -2.4
      RR_calf_joint:
        kp: 25.0
        kd: 0.5
        default_pos: -2.4

rl_controller:
  ros__parameters:
    update_rate: 50 # Hz
    joint_names: [
      'FL_hip_joint', 
      'FR_hip_joint', 
      'RL_hip_joint', 
      'RR_hip_joint', 
      'FL_thigh_joint', 
      'FR_thigh_joint', 
      'RL_thigh_joint', 
      'RR_thigh_joint', 
      'FL_calf_joint', 
      'FR_calf_joint', 
      'RL_calf_joint', 
      'RR_calf_joint'
    ]
    imu_names: # only use one imu for RL observation
      - imu # refer to ros2 control xacro file
    waypoints_topic: "/waypoints"
    # Disabled: legacy cmd_vel command pipeline.
    cmd_vel_topic: "cmd_vel"
    cmd_vel_range_lin_vel_x: [-1.0, 1.0]  # m/s
    cmd_vel_range_lin_vel_y: [-1.0, 1.0]  # m/s
    cmd_vel_range_ang_vel_z: [-3.14, 3.14]  # rad/s

    
